/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-22 18:06:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.moamoa.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import moamoa.post.PostDTO;
import moamoa.post.PostDAO;
import java.util.*;
import java.sql.*;

public final class con_005fpostDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("moamoa.post.PostDTO");
    _jspx_imports_classes.add("moamoa.post.PostDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Recipe Moa Moa</title>\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- CSS Styles -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.typekit.net/puo4qmu.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/jquery-ui.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mypage/mypage.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/login_signup/signup.css\">\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100;200;300;400;500;600;700;800;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\">\r\n");
      out.write("        <!-- luna herina script start -->\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            !function (h, e, a, r, i, n, c) {\r\n");
      out.write("                c = function () {};\r\n");
      out.write("                i = e.createElement(a);\r\n");
      out.write("                i.async = !0;\r\n");
      out.write("                i.src = r;\r\n");
      out.write("                i.onload = c;\r\n");
      out.write("                n = e.getElementsByTagName(a)[0];\r\n");
      out.write("                n\r\n");
      out.write("                    .parentNode\r\n");
      out.write("                    .insertBefore(i, n);\r\n");
      out.write("                if (h.hearinaJs) {\r\n");
      out.write("                    c();\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("            }(window, document, 'script', '//cdn.hearina.com/js/luna_hearina_v.0.4.js');\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("            <h2 class=\"subtitle\" id=\"sub1\"style=\"padding-top:100px !important; \">레시피</h2>\r\n");
      out.write("                        <br>\r\n");
      out.write("				");

					String post_title=request.getParameter("postTitle");
					PostDTO dto = new PostDAO().getPost(post_title);
					
					//System.out.println(result.size());
				
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			function setText(){\r\n");
      out.write("				var title = \"");
      out.print(dto.getTitle() );
      out.write("\";\r\n");
      out.write("				var ingredient = \"");
      out.print(dto.getIngredient() );
      out.write("\";\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				opener.document.getElementById(\"pInput\").value =title;\r\n");
      out.write("				opener.document.getElementById(\"mealkit_title\").value = title;\r\n");
      out.write("				opener.document.getElementById(\"main_ingredient\").value = ingredient;\r\n");
      out.write("				\r\n");
      out.write("				/* opener.document.getElementById(\"mealkit_content\").innerHTML= content;\r\n");
      out.write("				opener.document.getElementById(\"mealkit_sort\").value = category; */\r\n");
      out.write("				window.close();\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("				<br>\r\n");
      out.write("				<table style=\"text-align: center; border: 1px solid #dddddd ; width: 100%; height: 600px;\">\r\n");
      out.write("				\r\n");
      out.write("						 <tr>\r\n");
      out.write("						 	<td>제목</td>\r\n");
      out.write("						 	<td id=\"title\" value=\"");
      out.print(dto.getTitle() );
      out.write('"');
      out.write('>');
      out.print(dto.getTitle() );
      out.write("</td>\r\n");
      out.write("						 </tr>\r\n");
      out.write("					     <br>\r\n");
      out.write("					     <tr>\r\n");
      out.write("					     	<td>날짜</td>\r\n");
      out.write("					     	<td>");
      out.print(dto.getDate() );
      out.write("</td>\r\n");
      out.write("					     </tr>\r\n");
      out.write("					     <br>\r\n");
      out.write("					     <tr>\r\n");
      out.write("					     	<td>재료</td>\r\n");
      out.write("					     	<td>");
      out.print(dto.getIngredient() );
      out.write("</td>\r\n");
      out.write("					     </tr>\r\n");
      out.write("					     <br>\r\n");
      out.write("					     <tr>\r\n");
      out.write("					     	<td>내용</td>\r\n");
      out.write("					     	<td>");
      out.print(dto.getContent() );
      out.write("</td>\r\n");
      out.write("					     </tr>\r\n");
      out.write("					     <br>\r\n");
      out.write("				</table>\r\n");
      out.write("					<input type=\"button\" id=\"Input\" class=\"box_btn w144 h45 fs15\" value=\"계약하기\" onclick=\"setText()\">\r\n");
      out.write("					\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("            <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.js\"></script>    \r\n");
      out.write("            <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery-ui.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery.slicknav.js\"></script>\r\n");
      out.write("            <script src=\"../js/mixitup.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/main.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery-ui.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/jquery.form.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/clipboard.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/swiper.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/slick.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/ion.rangeSlider.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/jquery.countdown.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/cookie.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/script.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/custom.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/goods.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/buy.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/member.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/order.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/site.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/giftCard.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/scm.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/review.js\"></script>\r\n");
      out.write("        </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
