/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-23 05:34:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.moamoa.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import moamoa.product.ProductDTO;
import moamoa.product.ProductDAO;
import moamoa.cart.CartDAO;
import moamoa.cart.CartDTO;
import java.util.ArrayList;

public final class paying_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("moamoa.product.ProductDAO");
    _jspx_imports_classes.add("moamoa.cart.CartDTO");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("moamoa.product.ProductDTO");
    _jspx_imports_classes.add("moamoa.cart.CartDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>결제하기</title>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"./resources/css/bootstrap.min.css\">\r\n");
      out.write("   ");

      //세션 ID값 가져오기
/*       String cartId = session.getId();
      DecimalFormat dFormat = new DecimalFormat("###,###");      //숫자를 천단위 구분 */
   
      out.write("\r\n");
      out.write("           <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/style.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.typekit.net/puo4qmu.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mypage/mypage.css\">\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("   <div class=\"jumbotron\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <h1 class=\"display-3\">결제하기</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <table width=100%>\r\n");
      out.write("            <tr>\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"padding-top: 50px;\">\r\n");
      out.write("         <!-- table-hover : 마우스 포인터가 있는 행의 배경을 바꾸어 눈에 띄도록 만들어진 클래스 -->\r\n");
      out.write("         <table class=\"table table-hover\">\r\n");
      out.write("         <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>상품</th>\r\n");
      out.write("               <th>가격</th>\r\n");
      out.write("               <th>수량</th>\r\n");
      out.write("               <th>소계</th>\r\n");
      out.write("               <th>비고</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");

				String product = request.getParameter("productTitle");
				System.out.println(product);
           		ProductDAO Pdao = new ProductDAO();
           		CartDAO Cdao = new CartDAO();
           		
				ProductDTO presult = Pdao.getProductByTitle(product);
				Cdao.addCart(presult);
				ArrayList<CartDTO> result = Cdao.getCartByid("bu");
               //int sum = 0;
               //세션 속성의 이름이 cardList인 세션 정보(장바구니에 담긴 물품 목록)를 가져와서 ArrayList에 대입
              // ArrayList<Product> cartList = (ArrayList<Product>)session.getAttribute("cardList");
               /* cart.jsp 파일에서 전체상품을 삭제하는 deleteCard.jsp에서 session.invalidate()를 호툴하게 되면
                  cartList는 null이 되기 때문에 아래와 같은 코드가 반드시 필요함. */
               /* if(cartList == null) {
                  cartList = new ArrayList<>();
               } */
               //상품 리스트 하나씩 출력하기
              /*  for(int i = 0; i < cartList.size(); i++) {
                  Product product = cartList.get(i);
                  int total = product.getUnitprice() * product.getQuantity();
                  sum += total; */
                  int sum = 0;
                  for(int i = 0; i<result.size(); i++){
  					/* ProductDTO product = listOfProduct.get(i); */
  					System.out.println(i);
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>");
      out.print( result.get(i).getMealkit_title() );
      out.write("</td>\r\n");
      out.write("               	<td>");
      out.print(result.get(i).getMealkit_count() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(result.get(i).getMealkit_price() );
      out.write("</td>\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

            sum += result.get(i).getMealkit_count()*result.get(i).getMealkit_price();
                 
                  }
            
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			function pay(){\r\n");
      out.write("\r\n");
      out.write("				location.href=\"../mainpage/index.html\"\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th></th>\r\n");
      out.write("               <th></th>\r\n");
      out.write("               <th>총액: ");
      out.print( sum );
      out.write(" </th>\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("               <th></th>\r\n");
      out.write("            </tr>\r\n");
      out.write("     	</tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("         \r\n");
      out.write("                 <div class=\"order_info\">\r\n");
      out.write("                        <div class=\"order_zone_tit\">\r\n");
      out.write("                            <h4>주문자 정보</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"order_table_type\">\r\n");
      out.write("                            <table class=\"table_left\">\r\n");
      out.write("                                <colgroup>\r\n");
      out.write("                                    <col style=\"width:15%;\">\r\n");
      out.write("                                    <col style=\"width:85%;\">\r\n");
      out.write("                                </colgroup>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\"><span class=\"important\">주문하시는 분</span></th>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"orderName\" id=\"orderName\" value=\"\" data-pattern=\"gdEngKor\" maxlength=\"20\"/>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <!-- <tr>\r\n");
      out.write("                                    <th scope=\"row\">전화번호</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" id=\"phoneNum\" name=\"orderPhone\" value=\"\" maxlength=\"20\" />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr> -->\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\"><span class=\"important\">휴대폰 번호</span></th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" id=\"mobileNum\" name=\"orderCellPhone\" value=\"\" maxlength=\"20\" />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\"><span class=\"important\">이메일</span></th>\r\n");
      out.write("                                    <td class=\"member_email\">\r\n");
      out.write("                                        <input type=\"text\" name=\"orderEmail\" value=\"\" />\r\n");
      out.write("                                        <select id=\"emailDomain\" class=\"chosen-select\">\r\n");
      out.write("                                            <option value=\"self\">직접입력</option>\r\n");
      out.write("                                            <option value=\"naver.com\">@naver.com</option>\r\n");
      out.write("                                            <option value=\"hanmail.net\">@hanmail.net</option>\r\n");
      out.write("                                            <option value=\"daum.net\">@daum.net</option>\r\n");
      out.write("                                            <option value=\"nate.com\">@nate.com</option>\r\n");
      out.write("                                            <option value=\"hotmail.com\">@hotmail.com</option>\r\n");
      out.write("                                            <option value=\"gmail.com\">@gmail.com</option>\r\n");
      out.write("                                            <option value=\"icloud.com\">@icloud.com</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                          <!-- //order_info -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"delivery_info\">\r\n");
      out.write("                        <div class=\"order_zone_tit\">\r\n");
      out.write("                            <h4>배송정보</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"order_table_type shipping_info\">\r\n");
      out.write("                            <table class=\"table_left shipping_info_table\">\r\n");
      out.write("                                <colgroup>\r\n");
      out.write("                                    <col style=\"width:15%;\">\r\n");
      out.write("                                    <col style=\"width:85%;\">\r\n");
      out.write("                                </colgroup>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">배송지 확인</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <div class=\"form_element\" >\r\n");
      out.write("                                           \r\n");
      out.write("                                                <span>\r\n");
      out.write("                                                    <input type=\"radio\" name=\"shipping\" id=\"shippingBasic\">\r\n");
      out.write("                                                    <label for=\"shippingBasic\" class=\"choice_s\">기본 배송지</label>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span style=\"margin-left:10px;\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"shipping\" id=\"shippingRecently\">\r\n");
      out.write("                                                    <label for=\"shippingRecently\" class=\"choice_s\">최근 배송지</label>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span style=\"margin-left:10px;\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"shipping\" id=\"shippingNew\">\r\n");
      out.write("                                                    <label for=\"shippingNew\" class=\"choice_s\">직접 입력</label>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span style=\"margin-left:10px;\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"shipping\" id=\"shippingSameCheck\">\r\n");
      out.write("                                                    <label for=\"shippingSameCheck\" class=\"choice_s\">주문자정보와 동일</label>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <!-- <span class=\"btn_gray_list\"><a href=\"#myShippingListLayer\" class=\"btn_gray_small btn_open_layer js_shipping\"><span>배송지 관리</span></a></span>\r\n");
      out.write("                                            <input type=\"hidden\" class=\"shipping-delivery-visit\" value=\"n\" /> -->\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <!-- <tr>\r\n");
      out.write("                                    <th scope=\"row\"><span class=\"important\">받으실분</span></th>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"receiverName\" data-pattern=\"gdEngKor\" maxlength=\"20\"/></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\"><span class=\"important\">받으실 곳</span></th>\r\n");
      out.write("                                    <td class=\"member_address\">\r\n");
      out.write("                                        <div class=\"address_postcode\">\r\n");
      out.write("                                            <input type=\"text\" name=\"receiverZonecode\" readonly=\"readonly\" />\r\n");
      out.write("                                            <input type=\"hidden\" name=\"receiverZipcode\"/>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn_post_search\" onclick=\"gd_postcode_search('receiverZonecode', 'receiverAddress', 'receiverZipcode');\">우편번호검색</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"address_input\">\r\n");
      out.write("                                            <input type=\"text\" name=\"receiverAddress\" readonly=\"readonly\"/>\r\n");
      out.write("                                            <input type=\"text\" name=\"receiverAddressSub\" />\r\n");
      out.write("                                        </div>\r\n");
      out.write("										<label class=\"c-blue\" id=\"isdawnLabel\" style=\"display: block;margin-top: 50px;color: #329cff !important;\"></label>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">전화번호</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" id=\"receiverPhone\" name=\"receiverPhone\" />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\"><span class=\"important\">휴대폰 번호</span></th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" id=\"receiverCellPhone\" name=\"receiverCellPhone\"/>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">배달 참고메시지</th>\r\n");
      out.write("                                    <td class=\"td_last_say\"><input type=\"text\" name=\"orderMemo\"/></td>\r\n");
      out.write("                                </tr> -->\r\n");
      out.write("                    <!-- 배송방법 -->\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                                        <div class=\"payment_progress\">\r\n");
      out.write("                        <div class=\"order_zone_tit\">\r\n");
      out.write("                            <h4>결제수단 선택 / 결제</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"payment_progress_list\">\r\n");
      out.write("                            <div class=\"js_pay_content\">\r\n");
      out.write("                                <!-- N : 일반결제 시작 -->\r\n");
      out.write("                                <div id=\"settlekind_general\" class=\"general_payment\">\r\n");
      out.write("                                    <dl>\r\n");
      out.write("                                        <dt>일반결제</dt>\r\n");
      out.write("                                        <dd>\r\n");
      out.write("                                            <div class=\"form_element\">\r\n");
      out.write("                                                <ul class=\"payment_progress_select\">\r\n");
      out.write("                                                    <li id=\"settlekindType_pc\">\r\n");
      out.write("                                                        <input type=\"radio\" id=\"settleKind_pc\" name=\"settleKind\" value=\"pc\"/>\r\n");
      out.write("                                                        <label for=\"settleKind_pc\" class=\"choice_s\">신용카드</label>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li id=\"settlekindType_pb\">\r\n");
      out.write("                                                        <input type=\"radio\" id=\"settleKind_pb\" name=\"settleKind\" value=\"pb\"/>\r\n");
      out.write("                                                        <label for=\"settleKind_pb\" class=\"choice_s\">계좌이체</label>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li id=\"settlekindType_pv\">\r\n");
      out.write("                                                        <input type=\"radio\" id=\"settleKind_pv\" name=\"settleKind\" value=\"pv\"/>\r\n");
      out.write("                                                        <label for=\"settleKind_pv\" class=\"choice_s\">가상계좌</label>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li id=\"settlekindType_ph\">\r\n");
      out.write("                                                        <input type=\"radio\" id=\"settleKind_ph\" name=\"settleKind\" value=\"ph\"/>\r\n");
      out.write("                                                        <label for=\"settleKind_ph\" class=\"choice_s\">휴대폰결제</label>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li id=\"settlekindType_pk\">\r\n");
      out.write("                                                        <input type=\"radio\" id=\"settleKind_pk\" name=\"settleKind\" value=\"pk\"/>\r\n");
      out.write("                                                        <label for=\"settleKind_pk\" class=\"choice_s\">카카오페이</label>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <!-- //pay_bankbook_box -->\r\n");
      out.write("\r\n");
      out.write("                                            <!-- 신용카드 컨텐츠 -->\r\n");
      out.write("                                            <div class=\"card\" id=\"settlekind_general_pc\"></div>\r\n");
      out.write("                                            <!-- //신용카드 컨텐츠 -->\r\n");
      out.write("\r\n");
      out.write("                                            <!-- 계좌이체 컨텐츠 -->\r\n");
      out.write("                                            <div class=\"account-bank\" id=\"settlekind_general_pb\"></div>\r\n");
      out.write("                                            <!-- //계좌이체 컨텐츠 -->\r\n");
      out.write("\r\n");
      out.write("                                            <!-- 가상계좌 컨텐츠 -->\r\n");
      out.write("                                            <div class=\"virtual-bank\" id=\"settlekind_general_pv\"></div>\r\n");
      out.write("                                            <!-- //가상계좌 컨텐츠 -->\r\n");
      out.write("\r\n");
      out.write("                                            <!-- 휴대폰 컨텐츠 -->\r\n");
      out.write("                                            <div class=\"cellphone\" id=\"settlekind_general_ph\"></div>\r\n");
      out.write("                                            <!-- //휴대폰 컨텐츠 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        </dd>\r\n");
      out.write("                                    </dl>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- //general_payment -->\r\n");
      out.write("                                <!-- N : 일반결제 끝 -->\r\n");
      out.write("         \r\n");
      out.write("        		 <input type=\"button\" onclick=\"pay()\" value=\"결제하기\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr/>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
