/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-22 16:36:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.moamoa.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import moamoa.post.PostDAO;
import moamoa.post.PostDTO;
import java.util.*;
import java.sql.*;

public final class post_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("moamoa.post.PostDTO");
    _jspx_imports_classes.add("moamoa.post.PostDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Recipe Moa Moa</title>\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- CSS Styles -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.typekit.net/puo4qmu.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/jquery-ui.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mypage/mypage.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/login_signup/signup.css\">\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100;200;300;400;500;600;700;800;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\">\r\n");
      out.write("            \r\n");
      out.write("       <!-- luna herina script start -->\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            !function (h, e, a, r, i, n, c) {\r\n");
      out.write("                c = function () {};\r\n");
      out.write("                i = e.createElement(a);\r\n");
      out.write("                i.async = !0;\r\n");
      out.write("                i.src = r;\r\n");
      out.write("                i.onload = c;\r\n");
      out.write("                n = e.getElementsByTagName(a)[0];\r\n");
      out.write("                n\r\n");
      out.write("                    .parentNode\r\n");
      out.write("                    .insertBefore(i, n);\r\n");
      out.write("                if (h.hearinaJs) {\r\n");
      out.write("                    c();\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("            }(window, document, 'script', '//cdn.hearina.com/js/luna_hearina_v.0.4.js');\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div class=\"humberger__menu__overlay\"></div>\r\n");
      out.write("        <div class=\"humberger__menu__wrapper\">\r\n");
      out.write("            <div class=\"humberger__menu__logo\">\r\n");
      out.write("                <a href=\"#\">RECIPE MOA MOA</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"humberger__menu__cart\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"../indcompage/wish_list.html\">\r\n");
      out.write("                            <i class=\"fa fa-heart\"></i>\r\n");
      out.write("                            <span>1</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"../indcompage/order.html\">\r\n");
      out.write("                            <i class=\"fa fa-shopping-bag\"></i>\r\n");
      out.write("                            <span>3</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"header__cart__price\">총 주문가격\r\n");
      out.write("                    <span>15000</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"humberger__menu__widget\">\r\n");
      out.write("                <div class=\"header__top__right__auth\">\r\n");
      out.write("                    <a href=\"./login.html\">\r\n");
      out.write("                        <i class=\"fa fa-user\"></i>\r\n");
      out.write("                        로그인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"humberger__menu__nav mobile-menu\">\r\n");
      out.write("               <ul>\r\n");
      out.write("                                <li class=\"active\">\r\n");
      out.write("                                    <a href=\"../mainpage/index.html\">홈</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- <a href=\"../indcompage/shop_grid.html\">밀키트</a> -->\r\n");
      out.write("                                    <a href=\"../jsp/products.jsp\">밀키트</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- <a href=\"../indcompage/order.html\">주문하기</a> -->\r\n");
      out.write("                                    <a href=\"../jsp/cart.jsp\">주문하기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("<!--                                 <li>\r\n");
      out.write("                                    <a href=\"../indcompage/milkit_post_list.html\">게시판</a>\r\n");
      out.write("                                    <ul class=\"header__menu__dropdown\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"../indcompage/milkit_post_list.html\">레시피</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"../indcompage/milkitX_post_list.html\">자유</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"../indcompage/talk_list.html\">토크</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li> -->\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/post_list.jsp\">게시판</a>\r\n");
      out.write("                                    <ul class=\"header__menu__dropdown\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"../jsp/post_list.jsp\">레시피</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("            <div class=\"header__top__right__social\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <i class=\"fa fa-facebook\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <i class=\"fa fa-twitter\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <i class=\"fa fa-linkedin\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"humberger__menu__contact\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                        hello@bc.kr</li>\r\n");
      out.write("                    <li>10000이상 무료배송</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Humberger End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Header Section Begin -->\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header__top\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("                            <div class=\"header__top__left\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                                        hello@bc.kr</li>\r\n");
      out.write("                                    <li>10000이상 무료배송</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("                            <div class=\"header__top__right\">\r\n");
      out.write("                                <div class=\"header__top__right__social\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa fa-facebook\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa fa-twitter\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa fa-linkedin\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                               	<div class=\"header__top__right__auth\" class=\"open\">\r\n");
      out.write("                                    <a href=\"#a\" class=\"open\">\r\n");
      out.write("                                        <i class=\"fa fa-user\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"header__top__right__auth\">\r\n");
      out.write("                                    <a href=\"#a\" class=\"open\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"header__top__right__auth\">\r\n");
      out.write("                                    <a href=\"../jsp/contract.jsp\" class=\"open\">\r\n");
      out.write("                                        운영자</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"header__top__right__auth\">\r\n");
      out.write("                                    <a>\r\n");
      out.write("                                        ← 로그인</a> <!--이민영- 로그인하는 곳인 것을 알 수 있게 화살표 추가-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("<!--             이민영: 로그인 팝업창 div 코드 작성\r\n");
      out.write("            <div class=\"popup\">\r\n");
      out.write("                <body>\r\n");
      out.write("                    <section class=\"login\">\r\n");
      out.write("                      <h2>관리자 접속</h2>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <h5>관리자로 접속하시겠습니까?</h5>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <li><button onclick=\"location.href='../jsp/contract.jsp';\">관리자 접속</button></li>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                  </body>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"dim\"></div>\r\n");
      out.write("      -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"header__logo\">\r\n");
      out.write("                            <a href=\"../mainpage/index.html\"><img src=\"../img/logo2.png\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <nav class=\"header__menu\">\r\n");
      out.write("                                      <ul>\r\n");
      out.write("                                <li class=\"active\">\r\n");
      out.write("                                    <a href=\"../mainpage/index.html\">홈</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- <a href=\"../indcompage/shop_grid.html\">밀키트</a> -->\r\n");
      out.write("                                    <a href=\"../jsp/products.jsp\">밀키트</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- <a href=\"../indcompage/order.html\">주문하기</a> -->\r\n");
      out.write("                                    <a href=\"../jsp/cart.jsp\">주문하기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/post_list.jsp\">게시판</a>\r\n");
      out.write("                                    <ul class=\"header__menu__dropdown\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"../jsp/post_list.jsp\">레시피</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <!-- <div class=\"header__cart\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../indcompage/wish_list.html\">\r\n");
      out.write("                                        <i class=\"fa fa-heart\"></i>\r\n");
      out.write("                                        <span>1</span></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../indcompage/order.html\">\r\n");
      out.write("                                        <i class=\"fa fa-shopping-bag\"></i>\r\n");
      out.write("                                        <span>3</span></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"header__cart__price\">총 주문가격\r\n");
      out.write("                                <span>15000</span></div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"humberger__open\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"hero\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"hero__categories\">\r\n");
      out.write("                            <div class=\"hero__categories__all\">\r\n");
      out.write("                                <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                                <span>카테고리</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/category.jsp?category_name=korean_food\">한식</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/category.jsp?category_name=western_food\">양식</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/category.jsp?category_name=japanese_food\">일식</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/category.jsp?category_name=chinese_food\">중식</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/category.jsp?category_name=dessert\">디저트</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"../jsp/category.jsp?category_name=etc\">기타</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-9\">\r\n");
      out.write("                        <div class=\"hero__search\">\r\n");
      out.write("                            <div class=\"hero__search__form\">\r\n");
      out.write("                                <form action=\"../jsp/search.jsp\">\r\n");
      out.write("                                    <input type=\"text\" name=\"search_keyword\" placeholder=\"무엇을 검색하시겠습니까?\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"site-btn\">찾기</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"hero__search__phone\">\r\n");
      out.write("                                <div class=\"hero__search__phone__icon\">\r\n");
      out.write("                                    <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"hero__search__phone__text\">\r\n");
      out.write("                                    <h5>010-1234-5678</h5>\r\n");
      out.write("                                    <span>매일 24시간 전화 가능</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("            <h2 class=\"subtitle\" id=\"sub1\"style=\"padding-top:100px !important; \">레시피 게시판</h2>\r\n");
      out.write("                        <br>\r\n");
      out.write("				");

					PostDAO dao = new PostDAO();
					List<PostDTO> result = dao.getAllPostDatas();
					//System.out.println(result.size());
				
      out.write("\r\n");
      out.write("				<table style=\"text-align: center; border: 1px solid #dddddd ; width: 100%; height: 600px;\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>제목</th>\r\n");
      out.write("						<th>날짜</th>\r\n");
      out.write("						<th>내용</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");
for(int i=0; i< result.size(); i++){
      out.write("\r\n");
      out.write("							 <tr>\r\n");
      out.write("							 <td><a href=\"postDetail.jsp?postTitle=");
      out.print( result.get(i).getTitle());
      out.write('"');
      out.write('>');
      out.print(result.get(i).getTitle() );
      out.write("</a></td>\r\n");
      out.write("						     <td>");
      out.print(result.get(i).getDate() );
      out.write("</td>\r\n");
      out.write("						     <td style=\"overflow:hidden;white-space:nowrap;text-overflow:ellipsis;max-width:280px; padding:20px;\">");
      out.print(result.get(i).getContent() );
      out.write("</td>\r\n");
      out.write("						     </tr>\r\n");
      out.write("						");
	 
						} 
						
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				<hr>\r\n");
      out.write("					<span class=\"box_btn w144 h45 fs15\"><a href=\"../indcompage/post_write.html\">글쓰기</a></span>\r\n");
      out.write("					\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("            <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.js\"></script>    \r\n");
      out.write("            <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery-ui.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery.slicknav.js\"></script>\r\n");
      out.write("            <script src=\"../js/mixitup.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/main.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("            <script src=\"../js/jquery-ui.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/jquery.form.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/clipboard.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/swiper.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/slick.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/ion.rangeSlider.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/jquery.countdown.min.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/cookie.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/script.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/custom.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/goods.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/buy.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/member.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/order.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/site.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/giftCard.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/scm.js\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"../js/review.js\"></script>\r\n");
      out.write("        </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
